// resources/js/Pages/User/Profile/Index.jsx
import React, { useState } from 'react';
import { Head, useForm } from '@inertiajs/react';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';

export default function UserProfile({ auth, history }) {
    const user = auth.user;
    const [activeTab, setActiveTab] = useState('data'); // State untuk Tab (Data vs History)

    // Setup Form
    const { data, setData, put, processing, errors } = useForm({
        name: user.name,
        phone: user.phone || '',
        address: user.address || '',
        password: '',
        photo: null,
    });

    const [preview, setPreview] = useState(
        user.photo ? `/storage/${user.photo}` : '/img/default-user.png'
    );

    const handleImageChange = (e) => {
        const file = e.target.files[0];
        if (file) {
            setData('photo', file);
            setPreview(URL.createObjectURL(file));
        }
    };

    const submit = (e) => {
        e.preventDefault();
        put(route('user.profile.update'));
    };

    return (
        <AuthenticatedLayout
            user={auth.user}
            header={<h2 className="font-semibold text-xl text-gray-800 leading-tight">Profil Peserta</h2>}
        >
            <Head title="Profil Saya" />

            <div className="py-12">
                <div className="max-w-5xl mx-auto sm:px-6 lg:px-8">
                    <div className="bg-white overflow-hidden shadow-xl sm:rounded-lg flex flex-col md:flex-row">
                        
                        {/* Kolom Kiri: Ringkasan */}
                        <div className="w-full md:w-1/3 bg-gray-50 p-8 border-r border-gray-200 flex flex-col items-center text-center">
                            <div className="relative group mb-4">
                                <img 
                                    src={preview} 
                                    className="w-40 h-40 rounded-full object-cover shadow-lg border-4 border-white"
                                />
                                <label className="absolute bottom-2 right-2 bg-green-500 text-white p-2 rounded-full cursor-pointer hover:bg-green-600 transition shadow">
                                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                                        <path fillRule="evenodd" d="M4 5a2 2 0 00-2 2v8a2 2 0 002 2h12a2 2 0 002-2V7a2 2 0 00-2-2h-1.586a1 1 0 01-.707-.293l-1.414-1.414A1 1 0 0011.586 3H8.414a1 1 0 00-.707.293L6.293 4.707A1 1 0 015.586 5H4zm6 9a3 3 0 100-6 3 3 0 000 6z" clipRule="evenodd" />
                                    </svg>
                                    <input type="file" className="hidden" onChange={handleImageChange} accept="image/*" />
                                </label>
                            </div>
                            
                            <h2 className="text-2xl font-bold text-gray-800">{user.name}</h2>
                            <p className="text-gray-500 mb-4">Peserta Tryout</p>
                            
                            <div className="w-full text-left mt-4 pl-4 border-l-4 border-green-500 bg-white p-3 shadow-sm rounded">
                                <p className="text-sm text-gray-600 mb-1"><span className="font-bold">Email:</span> {user.email}</p>
                                <p className="text-sm text-gray-600"><span className="font-bold">HP:</span> {user.phone || '-'}</p>
                            </div>
                        </div>

                        {/* Kolom Kanan: Tabs & Content */}
                        <div className="w-full md:w-2/3 p-8">
                            {/* Navigasi Tab */}
                            <div className="flex border-b border-gray-200 mb-6">
                                <button 
                                    onClick={() => setActiveTab('data')}
                                    className={`py-2 px-4 font-medium transition-colors duration-200 ${activeTab === 'data' ? 'border-b-2 border-green-500 text-green-600' : 'text-gray-500 hover:text-gray-700'}`}
                                >
                                    Edit Data Diri
                                </button>
                                <button 
                                    onClick={() => setActiveTab('history')}
                                    className={`py-2 px-4 font-medium transition-colors duration-200 ${activeTab === 'history' ? 'border-b-2 border-green-500 text-green-600' : 'text-gray-500 hover:text-gray-700'}`}
                                >
                                    Riwayat Tryout
                                </button>
                            </div>

                            {/* Konten Tab: Data Form */}
                            {activeTab === 'data' && (
                                <form onSubmit={submit}>
                                    <div className="space-y-4">
                                        <div>
                                            <label className="block text-sm font-medium text-gray-700">Nama Lengkap</label>
                                            <input type="text" className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-green-500 focus:ring-green-500"
                                                value={data.name} onChange={(e) => setData('name', e.target.value)} />
                                            {errors.name && <div className="text-red-500 text-sm">{errors.name}</div>}
                                        </div>

                                        <div className="grid grid-cols-2 gap-4">
                                            <div>
                                                <label className="block text-sm font-medium text-gray-700">No. HP / WA</label>
                                                <input type="text" className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-green-500 focus:ring-green-500"
                                                    value={data.phone} onChange={(e) => setData('phone', e.target.value)} />
                                            </div>
                                            <div>
                                                <label className="block text-sm font-medium text-gray-700">Password Baru</label>
                                                <input type="password" className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-green-500 focus:ring-green-500"
                                                    value={data.password} onChange={(e) => setData('password', e.target.value)} placeholder="(Opsional)" />
                                            </div>
                                        </div>

                                        <div>
                                            <label className="block text-sm font-medium text-gray-700">Alamat</label>
                                            <textarea className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-green-500 focus:ring-green-500" rows="3"
                                                value={data.address} onChange={(e) => setData('address', e.target.value)}></textarea>
                                        </div>

                                        <div className="pt-4">
                                            <button type="submit" disabled={processing} className="w-full flex justify-center py-2 px-4 border border-transparent rounded-full shadow-sm text-sm font-medium text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500">
                                                Simpan Profil
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            )}

                            {/* Konten Tab: History */}
                            {activeTab === 'history' && (
                                <div className="space-y-4">
                                    {history.length > 0 ? (
                                        history.map((item) => (
                                            <div key={item.id} className="flex justify-between items-center bg-gray-50 p-4 rounded-lg border border-gray-200">
                                                <div>
                                                    <h4 className="font-bold text-gray-800">{item.name}</h4>
                                                    <p className="text-sm text-gray-500">📅 {item.date}</p>
                                                </div>
                                                <div className="text-right">
                                                    <span className="block text-xs text-gray-500 uppercase font-bold">Skor</span>
                                                    <span className={`text-xl font-bold ${item.score >= 400 ? 'text-green-600' : 'text-yellow-600'}`}>
                                                        {item.score}
                                                    </span>
                                                </div>
                                            </div>
                                        ))
                                    ) : (
                                        <div className="text-center py-8 text-gray-500">
                                            <p>Belum ada riwayat tryout.</p>
                                        </div>
                                    )}
                                </div>
                            )}

                        </div>
                    </div>
                </div>
            </div>
        </AuthenticatedLayout>
    );
}

// resources/js/Pages/User/Profile/Index.vue
<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, useForm, usePage } from '@inertiajs/vue3';
import { ref } from 'vue';

const props = defineProps({
    history: Array,
});

const user = usePage().props.auth.user;
const activeTab = ref('data'); // State untuk Tab ('data' atau 'history')

const form = useForm({
    name: user.name,
    phone: user.phone || '',
    address: user.address || '',
    password: '',
    photo: null,
});

// Default image jika user belum punya foto
const photoPreview = ref(user.photo ? `/storage/${user.photo}` : 'https://ui-avatars.com/api/?name=' + user.name);

const handlePhotoChange = (event) => {
    const file = event.target.files[0];
    if (file) {
        form.photo = file;
        photoPreview.value = URL.createObjectURL(file);
    }
};

const submit = () => {
    form.post(route('user.profile.update'), {
        preserveScroll: true,
        onSuccess: () => form.reset('password'),
    });
};
</script>

<template>
    <Head title="Profil Peserta" />

    <AuthenticatedLayout>
        <template #header>
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">Profil Saya</h2>
        </template>

        <div class="py-12">
            <div class="max-w-5xl mx-auto sm:px-6 lg:px-8">
                <div class="bg-white overflow-hidden shadow-xl sm:rounded-2xl flex flex-col md:flex-row">
                    
                    <div class="w-full md:w-1/3 bg-gray-50 p-8 border-r border-gray-100 flex flex-col items-center text-center">
                        <div class="relative group mb-5">
                            <img 
                                :src="photoPreview" 
                                class="w-40 h-40 rounded-full object-cover shadow-md border-4 border-white"
                            />
                            <label class="absolute bottom-2 right-2 bg-green-500 text-white p-2 rounded-full cursor-pointer hover:bg-green-600 transition shadow-sm">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 9a2 2 0 012-2h.93a2 2 0 001.664-.89l.812-1.22A2 2 0 0110.07 4h3.86a2 2 0 011.664.89l.812 1.22A2 2 0 0018.07 7H19a2 2 0 012 2v9a2 2 0 01-2 2H5a2 2 0 01-2-2V9z" />
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 13a3 3 0 11-6 0 3 3 0 016 0z" />
                                </svg>
                                <input type="file" class="hidden" @change="handlePhotoChange" accept="image/*" />
                            </label>
                        </div>
                        
                        <h2 class="text-2xl font-bold text-gray-800">{{ user.name }}</h2>
                        <p class="text-gray-500 mb-6 font-medium">Pejuang NIP 2025</p>
                        
                        <div class="w-full bg-white p-4 rounded-xl shadow-sm border border-gray-100 text-left">
                            <div class="text-xs text-gray-400 uppercase font-bold tracking-wider mb-2">Kontak</div>
                            <p class="text-sm text-gray-600 mb-1 flex items-center">
                                <span class="mr-2">📧</span> {{ user.email }}
                            </p>
                            <p class="text-sm text-gray-600 flex items-center">
                                <span class="mr-2">📱</span> {{ user.phone || '-' }}
                            </p>
                        </div>
                    </div>

                    <div class="w-full md:w-2/3 p-8">
                        
                        <div class="flex space-x-6 border-b border-gray-200 mb-6">
                            <button 
                                @click="activeTab = 'data'"
                                :class="{'border-b-2 border-green-500 text-green-600': activeTab === 'data', 'text-gray-500 hover:text-gray-700': activeTab !== 'data'}"
                                class="pb-2 font-medium text-lg transition-colors duration-200"
                            >
                                Edit Data Diri
                            </button>
                            <button 
                                @click="activeTab = 'history'"
                                :class="{'border-b-2 border-green-500 text-green-600': activeTab === 'history', 'text-gray-500 hover:text-gray-700': activeTab !== 'history'}"
                                class="pb-2 font-medium text-lg transition-colors duration-200"
                            >
                                Riwayat Tryout
                            </button>
                        </div>

                        <div v-if="activeTab === 'data'">
                            <form @submit.prevent="submit" class="space-y-5">
                                <div>
                                    <label class="block text-sm font-medium text-gray-700">Nama Lengkap</label>
                                    <input type="text" v-model="form.name" class="mt-1 block w-full rounded-xl border-gray-300 shadow-sm focus:border-green-500 focus:ring-green-500 transition bg-gray-50 focus:bg-white" />
                                    <div v-if="form.errors.name" class="text-red-500 text-xs mt-1">{{ form.errors.name }}</div>
                                </div>

                                <div class="grid grid-cols-1 md:grid-cols-2 gap-5">
                                    <div>
                                        <label class="block text-sm font-medium text-gray-700">No. WhatsApp</label>
                                        <input type="text" v-model="form.phone" class="mt-1 block w-full rounded-xl border-gray-300 shadow-sm focus:border-green-500 focus:ring-green-500 transition bg-gray-50 focus:bg-white" placeholder="0812..." />
                                    </div>
                                    <div>
                                        <label class="block text-sm font-medium text-gray-700">Password Baru</label>
                                        <input type="password" v-model="form.password" class="mt-1 block w-full rounded-xl border-gray-300 shadow-sm focus:border-green-500 focus:ring-green-500 transition bg-gray-50 focus:bg-white" placeholder="(Opsional)" />
                                    </div>
                                </div>

                                <div>
                                    <label class="block text-sm font-medium text-gray-700">Alamat Domisili</label>
                                    <textarea v-model="form.address" rows="3" class="mt-1 block w-full rounded-xl border-gray-300 shadow-sm focus:border-green-500 focus:ring-green-500 transition bg-gray-50 focus:bg-white"></textarea>
                                </div>

                                <div class="pt-2">
                                    <button 
                                        type="submit" 
                                        :disabled="form.processing"
                                        class="w-full flex justify-center py-3 px-4 border border-transparent rounded-xl shadow-md text-sm font-bold text-white bg-green-500 hover:bg-green-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500 transition transform active:scale-95"
                                    >
                                        {{ form.processing ? 'Menyimpan...' : 'Simpan Profil' }}
                                    </button>
                                </div>
                            </form>
                        </div>

                        <div v-if="activeTab === 'history'">
                            <div v-if="history.length > 0" class="space-y-3">
                                <div v-for="item in history" :key="item.id" class="flex items-center justify-between bg-white p-4 rounded-xl border border-gray-200 hover:shadow-md transition">
                                    <div class="flex items-center space-x-4">
                                        <div class="bg-green-100 p-3 rounded-lg text-green-600">
                                            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4" />
                                            </svg>
                                        </div>
                                        <div>
                                            <h4 class="font-bold text-gray-800">{{ item.name }}</h4>
                                            <p class="text-xs text-gray-500">{{ item.date }}</p>
                                        </div>
                                    </div>
                                    <div class="text-right">
                                        <div class="text-xs text-gray-400 uppercase font-bold">Skor</div>
                                        <div class="text-xl font-extrabold" :class="item.score >= 400 ? 'text-green-600' : 'text-yellow-500'">
                                            {{ item.score }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <div v-else class="text-center py-10">
                                <div class="bg-gray-100 rounded-full h-20 w-20 flex items-center justify-center mx-auto mb-4">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="h-10 w-10 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                                    </svg>
                                </div>
                                <h3 class="text-gray-500 font-medium">Belum ada riwayat tryout</h3>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </AuthenticatedLayout>
</template>
